language: python
python:
  - "3.6.5"
install: 
  - pip install -r requirements.txt
  - pip install pytest-cov
 


# command to run tests
script: 
      -py.test --cov=tests

after_success:
  - coveralls
  - codecov


