language: python
python:
  - "3.6.5"
install: 
  - pip install -r requirements.txt
  - pip install pytest-cov

services:
  - postgresql
env:
  global:
   - test_env="testing"

before_script:
  - sudo psql -c 'CREATE ROLE lubwama SUPERUSER LOGIN CREATEDB;' -U postgres
  - "psql -c 'create database Store_db;'-U postgres"


 


# command to run tests
script: 
      - py.test --cov=tests

after_success:
  - coveralls
  - codecov


